### ISSUE TITLE
Release an installable apk in release

### ISSUE THREAD

**Issue by yhs0602** [lhwdev/ASM#12]
I can't build the project because of some syntax errors.

So/anyway could you please release an instalkable apk to release so that others can test your app?

**Comment by gongbj0113** [comment]
Thank you for your interest in our ASM project ^^ 

We're sorry but our project is in developing and there's no released app that can be used yet.

Anyway, there is the testing app - It is 'gradle test' - now. If you need it, Goto this link : 

https://drive.google.com/file/d/1mbCQc_KyAvyRBu2yD1PMRSbsBtimox_n/view?usp=drivesdk

BUT, please understand it's not working well because I didn't finished it.

**Comment by lhwdev** [comment]
Hmm... Sorry but we're not uploading completed source. We use this repo only for developing, yet.
App from @GonngBJ is just a gradle testing app, and we didn't made main UI.
But I am making and reviewing them on my repo, https://github.com/lhwdev/ASM-preview (actually more buggy then here but more features?) and we're going to support **Plugin API** for developer to make plugins for ASM. It is stub; just an outline and don't make plugins for that API, (might you didn't want) because it isn't unstable.
_However, does there anyone make plugins?_
_If not, our team can make plugins! **xD**_

**Comment by thka2016** [comment]
https://github.com/lhwdev/ASM-preview can't open? Or is it private

**Comment by lhwdev** [comment]
@userr2019 Actually, that repo is deleted and our workspace is hidden(in gitlab); only codes related to asmx(plugin + theme + ...) will be published here.

Sorry for lack of latest document, we are developing hard but not professional developers.

**Comment by thka2016** [comment]
@lhwdev  if there is a preview to try, or as a tester. In fact, I pay attention to this project for a long time, have been hoping that this project will be better and better, support 👍 👍 👍

**Comment by lhwdev** [comment]
@userr2019 Thank you! We've been developing this for a long time, and will take so much time. But I'll notice you when any preview or testing available!

**Comment by thka2016** [comment]
@lhwdev OK, I'll keep an eye on you projects

**Comment by userr2019** [comment]
Is there any progress about asm project recently? I'm looking forward to using it.

**Comment by thka2016** [comment]
Is there any progress about asm project recently? I look forward to being his user.

**Comment by lhwdev** [comment]
@userr2019 We're students so don't have enough times to develop.. I would develop hardly if I had enough time.

**Comment by thka2016** [comment]
@lhwdev is this project suspended or abandoned?

**Comment by lhwdev** [comment]
@userr2019 No, just inactive a little. We actually started this project for fun. (now: for fun + some responsibility(?))

**Comment by thka2016** [comment]
@lhwdev come on! I will always follow and support you

**Comment by lhwdev** [comment]
@userr2019 Thanks! I'll try to release as soon as possible.

**Comment by thka2016** [comment]
@lhwdev thank you

**Comment by lhwdev** [comment]
@userr2019 Also our main workspace is [Gitlab](https://gitlab.com/asm-ide).

**Comment by thka2016** [comment]
I haven't used Gitlab, I can't read it, I've been using Github

**Comment by thka2016** [comment]
But I'll keep an eye on it.
